changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking
    - title: 📦 Features
      labels:
        - "*"
      exclude:
        labels:
          - bug
          - cosmetic
          - internal
          - dependencies
    - title: 🎷🐛 Bug Fixes
      labels:
        - bug
    - title: 💅 Cosmetic Changes
      labels:
        - cosmetic
    - title: 🥷 Internal Changes
      labels:
        - internal
    - title: 🗄️ Dependencies
      labels:
        - dependencies
